/** Merchant names for generated mock transactions. */
export const MERCHANTS = [
  "Whole Foods Market",
  "Trader Joe's",
  "Shell Gas",
  "Uber",
  "Lyft",
  "Netflix",
  "Spotify",
  "Amazon",
  "Target",
  "CVS Pharmacy",
  "Starbucks",
  "Blue Bottle Coffee",
  "Landlord LLC",
  "ConEd Utilities",
  "Metro Transit",
  "Equinox Gym",
  "Apple Store",
  "IKEA",
  "Delta Airlines",
  "Airbnb",
  "Payroll — Acme Corp",
  "Venmo Transfer",
  "ATM Withdrawal",
  "Interest Payment",
  "Home Depot",
  "Costco",
  "Chipotle",
  "Sweetgreen",
  "Dry Cleaners Co",
  "Pet Supplies Plus",
] as const;
